# Generated by Django 5.2.11 on 2026-02-21 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("item_not_received", "Товар не получен"),
                            (
                                "item_not_as_described",
                                "Товар не соответствует описанию",
                            ),
                            ("seller_unresponsive", "Продавец не отвечает"),
                            ("payment_issue", "Проблема с оплатой"),
                            ("fraud_suspected", "Подозрение на мошенничество"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Детально опишите проблему",
                        verbose_name="Описание проблемы",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыт"),
                            ("under_review", "На рассмотрении"),
                            ("resolved_buyer", "Решен в пользу покупателя"),
                            ("resolved_seller", "Решен в пользу продавца"),
                            ("resolved_partial", "Частичное решение"),
                            ("closed", "Закрыт"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "moderator_decision",
                    models.TextField(blank=True, verbose_name="Решение модератора"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Сумма для возврата покупателю (если применимо)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Сумма возврата",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата решения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Диспут",
                "verbose_name_plural": "Диспуты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Скриншот"),
                            ("chat_log", "Лог переписки"),
                            ("video", "Видео"),
                            ("other", "Другое"),
                        ],
                        default="screenshot",
                        max_length=20,
                        verbose_name="Тип доказательства",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="dispute_evidences/", verbose_name="Файл"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Доказательство",
                "verbose_name_plural": "Доказательства",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Скриншот или другое доказательство",
                        null=True,
                        upload_to="disputes/",
                        verbose_name="Вложение",
                    ),
                ),
                (
                    "is_moderator_message",
                    models.BooleanField(
                        default=False, verbose_name="Сообщение модератора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение в диспуте",
                "verbose_name_plural": "Сообщения в диспутах",
                "ordering": ["created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="payments_tr_user_id_d7ba42_idx",
            old_name="payments_tr_user_id_a4b8d9_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="payments_tr_status_7127e3_idx",
            old_name="payments_tr_status_c8e9f1_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="payments_tr_payment_750630_idx",
            old_name="payments_tr_payment_d2a3c4_idx",
        ),
        migrations.AddField(
            model_name="dispute",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Модератор, который рассматривает диспут",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Назначен модератору",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="escrow",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute",
                to="payments.escrow",
                verbose_name="Escrow сделка",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="opened_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes_opened",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Открыт пользователем",
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidences",
                to="payments.dispute",
                verbose_name="Диспут",
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_evidences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Загружено пользователем",
            ),
        ),
        migrations.AddField(
            model_name="disputemessage",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="payments.dispute",
                verbose_name="Диспут",
            ),
        ),
        migrations.AddField(
            model_name="disputemessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_dispute_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_di_status_45cb06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["assigned_to", "status"], name="payments_di_assigne_6b4349_idx"
            ),
        ),
    ]
