# Generated by Django 5.2.13 on 2026-05-07 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_dispute_disputeevidence_disputemessage_and_more'),
        ('transactions', '0007_purchaserequest_transaction_buyer_i_fc4c74_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['status', 'release_deadline'], name='escrow_status_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['buyer', '-created_at'], name='escrow_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['seller', '-created_at'], name='escrow_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', '-created_at'], name='tx_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status', '-created_at'], name='withdrawal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', '-created_at'], name='withdrawal_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative', violation_error_message='Баланс не может быть отрицательным'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('frozen_balance__gte', 0), ('frozen_balance__lte', models.F('balance'))), name='wallet_frozen_consistent', violation_error_message='Frozen balance должен быть в [0, balance]'),
        ),
    ]
