# Generated by Django 5.2.13 on 2026-05-23 15:48

from django.db import migrations, models

import core.validators
import payments.models_disputes


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_withdrawal_encryption_protect_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disputeevidence",
            name="file",
            field=models.FileField(
                help_text="Приватный storage; доступ только участникам спора и модератору.",
                storage=payments.models_disputes.DisputeEvidence._evidence_private_storage,
                upload_to="dispute_evidences/",
                validators=[core.validators.AttachmentValidator(max_size_mb=15)],
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="disputemessage",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Скриншот или другое доказательство. Приватный storage.",
                null=True,
                storage=payments.models_disputes.DisputeMessage._dispute_private_storage,
                upload_to="disputes/",
                validators=[core.validators.AttachmentValidator(max_size_mb=10)],
                verbose_name="Вложение",
            ),
        ),
    ]
