# Generated by Django 4.2.25 on 2025-10-27 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'Новое сообщение'), ('purchase_request', 'Запрос на покупку'), ('request_accepted', 'Запрос принят'), ('request_rejected', 'Запрос отклонен'), ('deal_completed', 'Сделка завершена'), ('new_review', 'Новый отзыв'), ('system', 'Системное уведомление')], max_length=30, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('link', models.CharField(blank=True, help_text='URL для перехода при клике', max_length=500, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['-created_at'], name='core_notifi_created_f19d5e_idx')],
            },
        ),
    ]
