# Generated by Django 5.2.11 on 2026-02-21 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("listings", "0014_listingreservation_pricehistory_priceoffer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntiFraudRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("blacklist_email", "Email в черном списке"),
                            ("blacklist_phone", "Телефон в черном списке"),
                            ("suspicious_price", "Подозрительная цена"),
                            ("rapid_account_creation", "Быстрое создание аккаунтов"),
                            (
                                "multiple_accounts_ip",
                                "Множественные аккаунты с одного IP",
                            ),
                            ("chargeback_history", "История чарджбеков"),
                        ],
                        max_length=50,
                        verbose_name="Тип правила",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Email, телефон, IP и т.д.",
                        max_length=500,
                        verbose_name="Паттерн",
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="0-100, где 100 = максимальный риск",
                        verbose_name="Оценка риска",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("flag", "Пометить"),
                            ("block", "Заблокировать"),
                            ("review", "На проверку"),
                        ],
                        default="flag",
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Правило антифрод",
                "verbose_name_plural": "Правила антифрод",
                "ordering": ["-risk_score"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Общие"),
                            ("trading", "Торговля"),
                            ("payments", "Платежи"),
                            ("security", "Безопасность"),
                            ("technical", "Технические"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотров"),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(default=0, verbose_name="Полезно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["category", "order", "question"],
            },
        ),
        migrations.CreateModel(
            name="DescriptionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название шаблона"),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="Используйте {переменные} для подстановки",
                        verbose_name="Шаблон",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text='Список переменных: ["level", "items", "price"]',
                        verbose_name="Переменные",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Использований"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_templates",
                        to="listings.game",
                        verbose_name="Игра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон описания",
                "verbose_name_plural": "Шаблоны описаний",
                "ordering": ["game", "-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="UserWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Причина")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warnings_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предупреждение",
                "verbose_name_plural": "Предупреждения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoModeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="listing, message, review и т.д.",
                        max_length=50,
                        verbose_name="Тип контента",
                    ),
                ),
                ("content_id", models.PositiveIntegerField(verbose_name="ID контента")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("hide", "Скрыто"),
                            ("flag", "Помечено"),
                            ("warn", "Предупреждение"),
                            ("block", "Заблокировано"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Причина")),
                (
                    "matched_patterns",
                    models.JSONField(
                        default=list, verbose_name="Обнаруженные паттерны"
                    ),
                ),
                (
                    "is_false_positive",
                    models.BooleanField(
                        default=False, verbose_name="Ложное срабатывание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automod_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automod_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомодерация",
                "verbose_name_plural": "Автомодерация",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_automo_user_id_98afed_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="core_automo_content_4ab41a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Модель"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="ID объекта"
                    ),
                ),
                ("field_name", models.CharField(max_length=100, verbose_name="Поле")),
                (
                    "old_value",
                    models.TextField(blank=True, verbose_name="Старое значение"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, verbose_name="Новое значение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог изменения данных",
                "verbose_name_plural": "Логи изменений данных",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "object_id", "-created_at"],
                        name="core_datach_model_n_d0607b_idx",
                    ),
                    models.Index(
                        fields=["changed_by", "-created_at"],
                        name="core_datach_changed_e0b0fc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModerationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("listing", "Объявление"),
                            ("review", "Отзыв"),
                            ("message", "Сообщение"),
                            ("profile", "Профиль"),
                        ],
                        max_length=50,
                        verbose_name="Тип контента",
                    ),
                ),
                ("content_id", models.PositiveIntegerField(verbose_name="ID контента")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("requires_changes", "Требует изменений"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Чем выше число, тем выше приоритет",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "moderator_comment",
                    models.TextField(blank=True, verbose_name="Комментарий модератора"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Рассмотрено"
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_queue",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Очередь модерации",
                "verbose_name_plural": "Очередь модерации",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-priority"],
                        name="core_modera_status_564289_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="core_modera_content_f33097_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Успешный вход"),
                            ("login_failed", "Неудачная попытка входа"),
                            ("logout", "Выход"),
                            ("password_change", "Смена пароля"),
                            ("password_reset_request", "Запрос сброса пароля"),
                            ("password_reset_complete", "Сброс пароля завершен"),
                            ("2fa_enabled", "2FA включена"),
                            ("2fa_disabled", "2FA отключена"),
                            ("balance_change", "Изменение баланса"),
                            ("withdrawal_request", "Запрос на вывод"),
                            ("withdrawal_complete", "Вывод завершен"),
                            ("deposit", "Пополнение"),
                            ("escrow_create", "Создание escrow"),
                            ("escrow_release", "Освобождение escrow"),
                            ("escrow_refund", "Возврат escrow"),
                            ("listing_create", "Создание объявления"),
                            ("listing_edit", "Редактирование объявления"),
                            ("listing_delete", "Удаление объявления"),
                            ("purchase_request", "Запрос на покупку"),
                            ("purchase_accept", "Принятие запроса"),
                            ("purchase_reject", "Отклонение запроса"),
                            ("purchase_complete", "Завершение сделки"),
                            ("review_create", "Создание отзыва"),
                            ("account_locked", "Блокировка аккаунта"),
                            ("account_unlocked", "Разблокировка аккаунта"),
                            ("suspicious_activity", "Подозрительная активность"),
                            ("rate_limit_exceeded", "Превышен лимит запросов"),
                            ("idor_attempt", "Попытка IDOR атаки"),
                            ("report_create", "Создание жалобы"),
                            ("profile_update", "Обновление профиля"),
                            ("email_change", "Смена email"),
                            ("phone_change", "Смена телефона"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=20,
                        verbose_name="Уровень риска",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Детальное описание действия", verbose_name="Описание"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные данные в JSON формате",
                        verbose_name="Метаданные",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Может быть NULL для анонимных действий",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог аудита безопасности",
                "verbose_name_plural": "Логи аудита безопасности",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_securi_user_id_d02b9b_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="core_securi_action__8759ba_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "-created_at"],
                        name="core_securi_risk_le_28c75f_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="core_securi_ip_addr_1f2ae9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ban_type",
                    models.CharField(
                        choices=[
                            ("temporary", "Временный"),
                            ("permanent", "Постоянный"),
                        ],
                        max_length=20,
                        verbose_name="Тип бана",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Спам"),
                            ("fraud", "Мошенничество"),
                            ("abuse", "Оскорбления"),
                            ("multiple_violations", "Множественные нарушения"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Причина",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Истекает"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "lifted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата снятия"
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bans_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бан",
                "verbose_name_plural": "Баны",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="core_userba_user_id_8db926_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_userba_expires_884372_idx"
                    ),
                ],
            },
        ),
    ]
