# Generated by Django 5.2.11 on 2026-02-22 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_antifraudrule_faq_descriptiontemplate_userwarning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'Новое сообщение'), ('purchase_request', 'Запрос на покупку'), ('request_accepted', 'Запрос принят'), ('request_rejected', 'Запрос отклонен'), ('deal_completed', 'Сделка завершена'), ('new_review', 'Новый отзыв'), ('price_offer', 'Новое предложение цены'), ('listing_reserved', 'Объявление зарезервировано'), ('dispute_resolved', 'Спор разрешен'), ('price_alert', 'Сработало уведомление о цене'), ('system', 'Системное уведомление')], max_length=30, verbose_name='Тип уведомления'),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_message', models.BooleanField(default=True, verbose_name='Email при новом сообщении')),
                ('email_purchase_request', models.BooleanField(default=True, verbose_name='Email при запросе на покупку')),
                ('email_price_offer', models.BooleanField(default=True, verbose_name='Email при предложении цены')),
                ('email_review', models.BooleanField(default=True, verbose_name='Email при новом отзыве')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='Push уведомления включены')),
                ('push_subscription', models.JSONField(blank=True, default=dict, verbose_name='Push subscription данные')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram уведомления')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram Chat ID')),
                ('digest_frequency', models.CharField(choices=[('realtime', 'Мгновенно'), ('hourly', 'Раз в час'), ('daily', 'Раз в день'), ('never', 'Никогда')], default='realtime', max_length=20, verbose_name='Частота сводок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.JSONField(verbose_name='Subscription Info')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Последнее использование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Push подписка',
                'verbose_name_plural': 'Push подписки',
                'ordering': ['-created_at'],
            },
        ),
    ]
