# Generated by Django 4.2.25 on 2025-10-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_report_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/', verbose_name='Изображение'),
        ),
    ]
