# Generated by Django 4.2.25 on 2025-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('reserved', 'Зарезервировано'), ('sold', 'Продано'), ('cancelled', 'Отменено')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['game', 'status'], name='listings_li_game_id_352e60_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status'], name='listings_li_seller__3237a3_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at', 'status'], name='listings_li_created_7fec3b_idx'),
        ),
    ]
