# Generated by Django 4.2.25 on 2025-10-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_add_fulltext_search"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="listing",
            name="listing_game_status_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listing_seller_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listing_status_price_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listing_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="listing",
            new_name="listings_li_search__219da8_gin",
            old_name="listing_search_vector_idx",
        ),
    ]
