# Generated by Django 5.2.7 on 2025-10-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_listing_listing_game_status_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('icon', models.CharField(blank=True, default='bi-tag', help_text='Например: bi-gem, bi-cart, bi-trophy, bi-star', max_length=50, verbose_name='Иконка Bootstrap Icons')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньше число = выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='listings.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['game', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория товара (например: Аккаунты, Гемы, Ключи)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.category', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['game', 'is_active'], name='listings_ca_game_id_1a8f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['game', 'order'], name='listings_ca_game_id_a81d95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('game', 'name')},
        ),
    ]
