# Generated by Django 5.2.7 on 2025-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_category_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Меньше число = выше в списке', verbose_name='Порядок сортировки'),
        ),
    ]
