# Generated by Django 5.2.11 on 2026-02-21 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_add_category_filters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Сколько часов зарезервировать",
                        verbose_name="Длительность (часы)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активно"),
                            ("expired", "Истекло"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
            ],
            options={
                "verbose_name": "Резервирование",
                "verbose_name_plural": "Резервирования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Старая цена"
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Новая цена"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "История цен",
                "verbose_name_plural": "История цен",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offered_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Предложенная цена",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Исходная цена"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Почему такая цена?",
                        max_length=500,
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                            ("countered", "Встречное предложение"),
                            ("expired", "Истекло"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "counter_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Встречная цена",
                    ),
                ),
                (
                    "counter_message",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Сообщение продавца"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата ответа"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Действительно до")),
            ],
            options={
                "verbose_name": "Предложение цены",
                "verbose_name_plural": "Предложения цен",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="categoryfilter",
            new_name="listings_ca_categor_afeb2b_idx",
            old_name="category_filter_cat_active_idx",
        ),
        migrations.RenameIndex(
            model_name="categoryfilter",
            new_name="listings_ca_categor_4ba3f5_idx",
            old_name="category_filter_cat_order_idx",
        ),
        migrations.RenameIndex(
            model_name="listingfiltervalue",
            new_name="listings_li_listing_29f3fc_idx",
            old_name="listing_filter_idx",
        ),
        migrations.RenameIndex(
            model_name="listingfiltervalue",
            new_name="listings_li_categor_3ab08f_idx",
            old_name="filter_value_text_idx",
        ),
        migrations.RenameIndex(
            model_name="listingfiltervalue",
            new_name="listings_li_categor_0e9a38_idx",
            old_name="filter_value_int_idx",
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Категория товара (необязательно)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="listings.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="listingreservation",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AddField(
            model_name="listingreservation",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="listings.listing",
                verbose_name="Объявление",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="listings.listing",
                verbose_name="Объявление",
            ),
        ),
        migrations.AddField(
            model_name="priceoffer",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_offers_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AddField(
            model_name="priceoffer",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_offers",
                to="listings.listing",
                verbose_name="Объявление",
            ),
        ),
        migrations.AddField(
            model_name="priceoffer",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_offers_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Продавец",
            ),
        ),
        migrations.AddIndex(
            model_name="listingreservation",
            index=models.Index(
                fields=["buyer", "status"], name="listings_li_buyer_i_1d7395_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingreservation",
            index=models.Index(
                fields=["listing", "status"], name="listings_li_listing_118acb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingreservation",
            index=models.Index(
                fields=["expires_at"], name="listings_li_expires_dbaec4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="listingreservation",
            unique_together={("listing", "buyer", "status")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["listing", "-changed_at"], name="listings_pr_listing_cf6d0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priceoffer",
            index=models.Index(
                fields=["buyer", "-created_at"], name="listings_pr_buyer_i_136061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priceoffer",
            index=models.Index(
                fields=["seller", "status", "-created_at"],
                name="listings_pr_seller__e34f76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="priceoffer",
            index=models.Index(
                fields=["listing", "-created_at"], name="listings_pr_listing_f4d21b_idx"
            ),
        ),
    ]
