# Generated by Django 5.2.12 on 2026-03-07 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0014_listingreservation_pricehistory_priceoffer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата просмотра"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="listings.listing",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История просмотра",
                "verbose_name_plural": "История просмотров",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-viewed_at"], name="listings_vi_user_id_ba19ed_idx"
                    ),
                    models.Index(
                        fields=["listing", "-viewed_at"], name="listings_vi_listing_2f9ef2_idx"
                    ),
                ],
                "unique_together": {("user", "listing")},
            },
        ),
    ]
