# Generated by Django 5.2.13 on 2026-05-07 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_favorite_listings_fa_user_id_286a0e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status', '-created_at'], name='listing_seller_active_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['game', 'category', 'status'], name='listing_game_cat_idx'),
        ),
    ]
