# Generated by Django 5.2.13 on 2026-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listing_listing_seller_active_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='funpay_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Идентификатор категории на funpay.com (для импорта/синхронизации)', max_length=20, verbose_name='FunPay ID'),
        ),
        migrations.AddField(
            model_name='game',
            name='funpay_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Идентификатор игры на funpay.com (для импорта/синхронизации)', max_length=20, verbose_name='FunPay ID'),
        ),
    ]
