# Generated by Django 5.2.13 on 2026-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0017_listing_listing_seller_active_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Идентификатор категории для импорта и синхронизации каталога",
                max_length=20,
                verbose_name="ID в каталоге",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Идентификатор игры для импорта и синхронизации каталога",
                max_length=20,
                verbose_name="ID в каталоге",
            ),
        ),
    ]
