# Generated by Django 4.2.25 on 2025-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='Содержимое'),
        ),
    ]
