# Generated by Django 4.2.25 on 2025-10-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_p1_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_p2_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_listing_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_conv_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_conv_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_sender_created_idx',
        ),
    ]
