# Generated by Django 5.2.12 on 2026-03-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_conversation_ordering_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Содержимое'),
        ),
    ]
