# Generated by Django 5.2.13 on 2026-05-07 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_image_to_message'),
        ('listings', '0017_listing_listing_seller_active_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant1', '-updated_at'], name='conv_p1_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant2', '-updated_at'], name='conv_p2_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read', 'sender'], name='msg_unread_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('participant1', 'participant2', 'listing'), name='unique_conversation_with_listing'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', True)), fields=('participant1', 'participant2'), name='unique_conversation_no_listing'),
        ),
    ]
