# Generated by Django 4.2.25 on 2025-10-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации'),
        ),
    ]
