# Generated by Django 4.2.25 on 2025-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
