# Generated by Django 4.2.25 on 2025-10-14 22:39
# Updated to use new AvatarValidator

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(
                blank=True, 
                null=True, 
                upload_to='avatars/', 
                validators=[core.validators.AvatarValidator()], 
                verbose_name='Аватар',
                help_text='Макс. 2 МБ. Форматы: JPG, PNG, WebP'
            ),
        ),
    ]
