# Generated by Django 4.2.25 on 2025-10-14 22:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[accounts.models.validate_avatar_size, accounts.models.validate_avatar_type], verbose_name='Аватар'),
        ),
    ]
