# Generated by Django 4.2.25 on 2025-10-27 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Токен верификации')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации')),
            ],
            options={
                'verbose_name': 'Верификация Email',
                'verbose_name_plural': 'Верификации Email',
            },
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profile_user_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profile_verified_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profile_top_sellers_idx',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
