# Generated by Django 4.2.25 on 2025-10-27 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Баланс",
            ),
        ),
    ]
