# Generated by Django 5.2.7 on 2025-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Права модератора (просмотр жалоб, удаление контента)', verbose_name='Модератор'),
        ),
    ]
