# Generated by Django 5.2.11 on 2026-02-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_social_networks"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profile",
            name="profile_last_seen_idx",
        ),
        migrations.AddField(
            model_name="profile",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Рекомендуемый размер: 1200x300px",
                null=True,
                upload_to="covers/",
                verbose_name="Обложка профиля",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Telegram Chat ID"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_notifications",
            field=models.BooleanField(
                default=False, verbose_name="Telegram уведомления"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresetcode",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Код подтверждения"),
        ),
    ]
