# Generated by Django 5.2.11 on 2026-02-22 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_profile_profile_last_seen_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, help_text='Desktop, Mobile, Tablet', max_length=50, verbose_name='Тип устройства')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Браузер')),
                ('location', models.CharField(blank=True, help_text='Город, страна', max_length=200, verbose_name='Местоположение')),
                ('success', models.BooleanField(default=True, verbose_name='Успешный вход')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина неудачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История входа',
                'verbose_name_plural': 'История входов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_lo_user_id_ef3169_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_lo_ip_addr_57e141_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('multiple_failed_logins', 'Множественные неудачные входы'), ('unusual_location', 'Необычное местоположение'), ('unusual_device', 'Необычное устройство'), ('too_many_requests', 'Слишком много запросов'), ('suspicious_purchase', 'Подозрительная покупка')], max_length=50, verbose_name='Тип активности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=20, verbose_name='Серьезность')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Разрешено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подозрительная активность',
                'verbose_name_plural': 'Подозрительная активность',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_su_user_id_1f2e63_idx'), models.Index(fields=['severity', 'is_resolved'], name='accounts_su_severit_b4cae5_idx')],
            },
        ),
    ]
