# Generated by Django 5.2.12 on 2026-03-07 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_loginhistory_suspiciousactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Паспорт'), ('id_card', 'ID карта'), ('driver_license', 'Водительские права'), ('selfie', 'Селфи с документом')], max_length=20, verbose_name='Тип документа')),
                ('document_file', models.FileField(help_text='Макс. 10 МБ. Форматы: JPG, PNG, PDF', upload_to='verification_documents/%Y/%m/', verbose_name='Файл документа')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Верификация документа',
                'verbose_name_plural': 'Верификации документов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_do_user_id_699e19_idx'), models.Index(fields=['status', 'created_at'], name='accounts_do_status_b28aab_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=6, verbose_name='Код верификации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Верификация телефона',
                'verbose_name_plural': 'Верификации телефонов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_verified'], name='accounts_ph_user_id_7c085f_idx'), models.Index(fields=['phone', 'is_verified'], name='accounts_ph_phone_35cd1c_idx')],
            },
        ),
    ]
