# Generated by Django 5.2.12 on 2026-04-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_data_export_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_verified'], name='accounts_pr_is_veri_3c14f3_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_moderator'], name='accounts_pr_is_mode_e63363_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-rating', '-total_sales'], name='accounts_pr_rating_fbda81_idx'),
        ),
    ]
