# Generated by Django 5.2.13 on 2026-05-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_accounts_pr_is_veri_3c14f3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
