# Generated by Django 5.2.13 on 2026-05-23 15:48

from django.db import migrations, models

import accounts.models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_passwordresetcode_attempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentverification",
            name="document_file",
            field=models.FileField(
                help_text="Макс. 10 МБ. Форматы: JPG, PNG, PDF. Хранится в приватном storage.",
                storage=accounts.models.DocumentVerification._kyc_storage,
                upload_to="verification_documents/%Y/%m/",
                validators=[core.validators.AttachmentValidator(max_size_mb=10)],
                verbose_name="Файл документа",
            ),
        ),
    ]
