# Generated by Django 4.2.25 on 2025-10-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchase_buyer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchase_seller_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchase_listing_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchase_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_reviewer_created_idx',
        ),
    ]
