# Generated by Django 6.0.3 on 2026-04-02 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_add_view_history_model'),
        ('transactions', '0005_dispute_disputeevidence_disputemessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaserequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('listing', 'buyer'), name='unique_active_purchase_per_buyer'),
        ),
    ]
