# Generated by Django 5.2.12 on 2026-04-18 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_favorite_listings_fa_user_id_286a0e_idx_and_more'),
        ('transactions', '0006_alter_purchaserequest_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['buyer', 'status'], name='transaction_buyer_i_fc4c74_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['seller', 'status'], name='transaction_seller__d4e0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['seller', '-completed_at'], name='transaction_seller__e7687d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewed_user', '-created_at'], name='transaction_reviewe_b50b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', '-created_at'], name='transaction_reviewe_782f5f_idx'),
        ),
    ]
