# Generated by Django 5.2.13 on 2026-05-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_purchaserequest_transaction_buyer_i_fc4c74_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата принятия"),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата отмены"),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата отклонения"),
        ),
    ]
