# Generated by Django 5.2.13 on 2026-05-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_add_timeline_timestamps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disputemessage",
            name="dispute",
        ),
        migrations.RemoveField(
            model_name="disputeevidence",
            name="dispute",
        ),
        migrations.RemoveField(
            model_name="disputeevidence",
            name="uploader",
        ),
        migrations.RemoveField(
            model_name="disputemessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="guaranteeservice",
            name="guarantor",
        ),
        migrations.RemoveField(
            model_name="guaranteeservice",
            name="purchase_request",
        ),
        migrations.DeleteModel(
            name="Dispute",
        ),
        migrations.DeleteModel(
            name="DisputeEvidence",
        ),
        migrations.DeleteModel(
            name="DisputeMessage",
        ),
        migrations.DeleteModel(
            name="GuaranteeService",
        ),
    ]
