# Generated by Django 5.2.13 on 2026-05-23 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_purchaserequest_amount_protect_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Snapshot цены listing на момент создания запроса. Эскроу фондируется именно на эту сумму, чтобы продавец не поднял цену между created и accepted.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Сумма сделки",
            ),
        ),
    ]
